---
- hosts: rocky
  user: sysadmin
  become: true

  tasks:

  - name: Install apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Enable apache
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true

  - name: Enable firewall ports
    ansible.posfix.firewalld:
      service:
        - http
        - https
      permanent: true
      state: enabled
      immediate: true

  - name: Install custom index.html w/template
    ansible.builtin.template:
      src: ./templates/index.j2
      dest: /var/www/html/index.html
      mode: '0444'
      owner: apache
      group: apache

